language: php

sudo: false

before_install:
    - composer self-update

install:
    - composer install --dev --prefer-source

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: nightly
        - php: hhvm
    fast_finish: true