language: php

sudo: false

before_install:
    - composer self-update

install:
    - composer install --dev
    - cp .env.dist .env

script: phpunit -c app

matrix:
    include:
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
    fast_finish: true